name: CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches: [ "**" ]

env:
  RUST_LOG: debug
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: "1"
  RUSTFLAGS: "-D warnings"

jobs:
  ci:
    name: CI

    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Fetch submodules
        run: |
          git submodule update --init
          git submodule foreach 'git fetch --tags'
      
      - run: |
          ls -alh
          ls -alh librdkafka
          cd librdkafka && git status && git log -n 10 && ls -alh .git

      - name: Setup rust
        run: |
          rustup self update
          rustup toolchain install
          rustup toolchain install nightly --component rustfmt

      # - name: Cargo fmt
      #   run: cargo +nightly fmt --all --check

      # - name: Cargo clippy
      #   run: cargo clippy --release

      - name: Cargo test
        run: cargo test --release -- --nocapture

      - name: Cargo doc
        run: cargo doc --all
